POST https://localhost:5001/api/courses/1/assignments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0IiwibmJmIjoxNjE3NDE1NjQ5LCJleHAiOjE2MTc0MjY0NDksImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjUwMDEiLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdDo1MDAxIn0.Im6VvrBumSPmlXNEm-mNjffLoEQdnxDbUlOMCtT5_u8 

{
  "courseId": "6",
  "title": "Advanced programming",
  "description": "Learn how to do some advanced things with databases!",
  "maxPoints": "8",
  "dueDate": "1986-02-09T15:53:00.000Z",
  "assignmentType": "File Upload"
}

### Delete Assignment

DELETE https://localhost:5001/api/courses/6/assignments/5
Authorization: Bearer <replace with authToken> 


### Get all assignments for a course
GET https://localhost:5001/api/courses/6/assignments
Authorization: Bearer <replace with authToken> 


###
PUT https://localhost:5001/api/courses/6/assignments
Content-Type: application/json
Authorization: Bearer <replace with authToken> 

{
  "courseId": "6",
  "assignmentId":"6",
  "title": "Updated Database Programming assignment",
  "description": "Learn how to do some advanced things with databases!",
  "maxPoints": "50",
  "dueDate": "1986-02-09T15:53:00.000Z",
  "assignmentType": "Text Entry"
}
