PUT https://localhost:5001/api/courses
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzIiwibmJmIjoxNjE2NzkzMzc0LCJleHAiOjE2MTY4MDQxNzQsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjUwMDEvIiwiYXVkIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NTAwMS8ifQ.s_fZFQL7NJYjczUOjuUrKTDok8QsRo4thwD3Hu9xdV8

{
  "courseId": "1",
  "courseName": "Advanced Database Programming",
  "courseNumber": "CS 3550",
  "instructorId": "1",
  "department": "Computer Science",
  "creditHours": "4",
  "description": "Learn how to do some advanced things with databases!",
  "buildingName": "Computer Science Building",
  "roomNumber": "CA 141",
  "meetingDays": "MWF",
  "startTime": "08:00 AM",
  "endTime": "11:30 AM",
  "maxCapacity": "30"
}

###

DELETE https://localhost:5001/api/courses/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0IiwibmJmIjoxNjE2Nzk4OTk1LCJleHAiOjE2MTY4MDk3OTUsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjUwMDEiLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdDo1MDAxIn0.MPceemQydnOkBolithhzwb6t8UWjGSLIb7X5mt-2NG4