### Signup
POST https://localhost:5001/api/auth/signup
Content-Type: application/json 

{
  "accountType": "instructor",
  "firstName": "Joe",
  "lastName": "Instructor",
  "email": "joe@lms.com",
  "birthDay": "1986-02-09T15:53:00.000Z",
  "password": "password"
}

### Login
POST https://localhost:5001/api/auth/login
Content-Type: application/json 

{
  "email": "123@gmail.com",
  "password": "12345"
}

### Protected Route
GET https://localhost:5001/api/users/current
Authorization: Bearer <replace with authToken> 

