PUT https://localhost:5001/api/users
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0IiwibmJmIjoxNjE2MTg2NjgxLCJleHAiOjE2MTYxOTc0ODEsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjUwMDEiLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdDo1MDAxIn0.ge2e7zWMEXnY73zyCu46QYwJyhqmFm2rR85nQD__dGU

{
  "accountType": "instructor",
  "email": "joe@lms.com",
  "firstName": "Joe",
  "lastName": "Instructor",
  "phoneNumber": "801-123-4567"
}